name: restbase
description: A rest client base to make API requests.
version: 0.4.0
homepage: https://github.com/iatecbr/flutter_rest

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: